name: Docker Compose CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and run containers
        run: |
          docker-compose up -d --build
          sleep 10
          docker ps
          curl http://localhost:3000

      # Simular fallo controlado (opcional)
      - name: Simulate backend failure
        run: |
          docker stop $(docker ps -q --filter "name=backend")
          sleep 5
          docker-compose up -d
